import Head from "next/head";
import { Inter } from "@next/font/google";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="p-4 text-center">
        <h1 className="text-5xl p-2 bg-gray-600 rounded">CSSで遊ぶ</h1>
        <h2>TODO</h2>
        <li>ダークモード</li>
        <li>クラス名共通化</li>
        <li>github</li>
      </main>
    </>
  );
}
